// _write_script.js - Writes the helper data files
const fs = require('fs');

// 1. Small-biz config generator block
const configBlock = [
  '// ' + '\u2500'.repeat(46),
  '// small-biz config.ts \uC0DD\uC131',
  '// ' + '\u2500'.repeat(46),
  '',
  'function buildMenuItemsArray(items: unknown[]): string {',
  "  if (!Array.isArray(items) || items.length === 0) return '[]';",
  '  const entries = items.map((item) => {',
  '    const v = item as Record<string, string>;',
  '    const lines: string[] = [',
  "      `    name: '${esc(v.name || '')}',`,",
  '    ];',
  "    if (v.nameEn) lines.push(`    nameEn: '${esc(v.nameEn)}',`);",
  "    lines.push(`    price: '${esc(v.price || '')}',`);",
  "    if (v.priceEn) lines.push(`    priceEn: '${esc(v.priceEn)}',`);",
  "    if (v.desc) lines.push(`    desc: '${esc(v.desc)}',`);",
  "    if (v.descEn) lines.push(`    descEn: '${esc(v.descEn)}',`);",
  "    if (v.category) lines.push(`    category: '${esc(v.category)}',`);",
  "    if (v.categoryEn) lines.push(`    categoryEn: '${esc(v.categoryEn)}',`);",
  "    if (v.imageUrl) lines.push(`    imageUrl: '${esc(v.imageUrl)}',`);",
  "    return `  {\n${lines.join('\n')}\n  }`;",
  '  });',
  "  return `[\n${entries.join(',\n')}\n]`;",
  '}',
  '',
  'function buildHoursArray(items: unknown[]): string {',
  "  if (!Array.isArray(items) || items.length === 0) return '[]';",
  '  const entries = items.map((item) => {',
  '    const v = item as Record<string, string>;',
  '    const lines: string[] = [',
  "      `    day: '${esc(v.day || '')}',`,",
  "      `    open: '${esc(v.open || '')}',`,",
  "      `    close: '${esc(v.close || '')}',`,",
  '    ];',
  "    if ((item as Record<string, unknown>).isHoliday) lines.push('    isHoliday: true,');",
  "    return `  {\n${lines.join('\n')}\n  }`;",
  '  });',
  "  return `[\n${entries.join(',\n')}\n]`;",
  '}',
  '',
  'export function generateSmallBizConfigTs(state: ModuleConfigState): string {',
  '  const hero = state.values.hero || {};',
  '  const menu = state.values.menu || {};',
  '  const hours = state.values.hours || {};',
  '  const location = state.values.location || {};',
  '  const gallery = state.values.gallery || {};',
  '  const sns = state.values.sns || {};',
  '',
  "  const name = (hero.name as string) || '\uB9DB\uC788\uB294 \uAC00\uAC8C';",
  "  const nameEn = (hero.nameEn as string) || 'Delicious Shop';",
  "  const description = (hero.description as string) || '\uC815\uC131\uC744 \uB2F4\uC740 \uC694\uB9AC\uB97C \uC81C\uACF5\uD569\uB2C8\uB2E4';",
  "  const descriptionEn = (hero.descriptionEn as string) || 'We serve food made with care';",
  "  const phone = (hero.phone as string) || '02-1234-5678';",
  "  const primaryColor = (hero.primaryColor as string) || '#d47311';",
  '',
  "  const address = (location.address as string) || '\uC11C\uC6B8\uC2DC \uAC15\uB0A8\uAD6C \uD14C\uD5E4\uB780\uB85C 123';",
  "  const addressEn = (location.addressEn as string) || '123 Teheran-ro, Gangnam-gu, Seoul';",
  "  const kakaoMapId = (location.kakaoMapId as string) || '';",
  '',
  '  const menuItems = (menu.items as unknown[]) || [];',
  '  const hoursItems = (hours.items as unknown[]) || [];',
  '  const galleryImages = (gallery.images as { url: string }[]) || [];',
  '',
  "  const instagramUrl = (sns.instagramUrl as string) || '';",
  "  const naverBlogUrl = (sns.naverBlogUrl as string) || '';",
  "  const kakaoChannelUrl = (sns.kakaoChannelUrl as string) || '';",
  '',
  '  const galleryArr = galleryImages.length > 0',
  "    ? '[\n' + galleryImages.map(img => `  '${esc(img.url || \"\")}'`).join(',\n') + '\n]'",
  "    : '[]';",
  '',
  '  return `export interface MenuItem {',
  '  name: string;',
  '  nameEn?: string;',
  '  price: string;',
  '  priceEn?: string;',
  '  desc?: string;',
  '  descEn?: string;',
  '  category?: string;',
  '  categoryEn?: string;',
  '  imageUrl?: string;',
  '}',
  '',
  'export interface BusinessHour {',
  '  day: string;',
  '  open: string;',
  '  close: string;',
  '  isHoliday?: boolean;',
  '}',
  '',
  'const DEMO_MENU: MenuItem[] = ${buildMenuItemsArray(menuItems)};',
  '',
  'const DEMO_HOURS: BusinessHour[] = ${buildHoursArray(hoursItems)};',
  '',
  'function parseJSON<T>(raw: string | undefined, fallback: T): T {',
  '  if (!raw) return fallback;',
  '  try {',
  '    return JSON.parse(raw) as T;',
  '  } catch {',
  '    return fallback;',
  '  }',
  '}',
  '',
  'export const siteConfig = {',
  "  name: process.env.NEXT_PUBLIC_SITE_NAME || '${esc(name)}',",
  "  nameEn: process.env.NEXT_PUBLIC_SITE_NAME_EN || '${esc(nameEn)}',",
  "  description: process.env.NEXT_PUBLIC_DESCRIPTION || '${esc(description)}',",
  "  descriptionEn: process.env.NEXT_PUBLIC_DESCRIPTION_EN || '${esc(descriptionEn)}',",
  "  phone: process.env.NEXT_PUBLIC_PHONE || ${phone ? `'${esc(phone)}'` : 'null'},",
  "  primaryColor: process.env.NEXT_PUBLIC_PRIMARY_COLOR || '${esc(primaryColor)}',",
  "  address: process.env.NEXT_PUBLIC_ADDRESS || '${esc(address)}',",
  "  addressEn: process.env.NEXT_PUBLIC_ADDRESS_EN || '${esc(addressEn)}',",
  "  kakaoMapId: process.env.NEXT_PUBLIC_KAKAO_MAP_ID || ${kakaoMapId ? `'${esc(kakaoMapId)}'` : 'null'},",
  '  menuItems: parseJSON<MenuItem[]>(process.env.NEXT_PUBLIC_MENU_ITEMS, DEMO_MENU),',
  '  businessHours: parseJSON<BusinessHour[]>(process.env.NEXT_PUBLIC_BUSINESS_HOURS, DEMO_HOURS),',
  '  galleryImages: parseJSON<string[]>(process.env.NEXT_PUBLIC_GALLERY_IMAGES, ${galleryArr}),',
  "  instagramUrl: process.env.NEXT_PUBLIC_INSTAGRAM_URL || ${instagramUrl ? `'${esc(instagramUrl)}'` : 'null'},",
  "  naverBlogUrl: process.env.NEXT_PUBLIC_NAVER_BLOG_URL || ${naverBlogUrl ? `'${esc(naverBlogUrl)}'` : 'null'},",
  "  kakaoChannelUrl: process.env.NEXT_PUBLIC_KAKAO_CHANNEL_URL || ${kakaoChannelUrl ? `'${esc(kakaoChannelUrl)}'` : 'null'},",
  '  gaId: process.env.NEXT_PUBLIC_GA_ID || null,',
  '};',
  '',
  'export type SiteConfig = typeof siteConfig;',
  '`;',
  '}',
  '',
].join('\n');

fs.writeFileSync('C:/Dev/linkmap/_smallbiz_config.txt', configBlock, 'utf8');
console.log('Wrote _smallbiz_config.txt:', configBlock.length, 'bytes');

// 2. SMALL_BIZ_MODULE_COMPONENTS
const componentsBlock = [
  '/** small-biz \uBAA8\uB4C8 ID \u2192 import/\uB80C\uB354 \uB9E4\uD551 */',
  'const SMALL_BIZ_MODULE_COMPONENTS: Record<',
  '  string,',
  '  { importName: string; importPath: string; render: string }',
  '> = {',
  '  hero: {',
  "    importName: 'HeroSection',",
  "    importPath: '@/components/hero-section',",
  "    render: '        <HeroSection config={siteConfig} />',",
  '  },',
  '  menu: {',
  "    importName: '
