import { NextRequest, NextResponse } from 'next/server';
import { createClient } from '@/lib/supabase/server';
import { decrypt } from '@/lib/crypto';
import { rateLimit } from '@/lib/rate-limit';
import { logAudit } from '@/lib/audit';

export async function GET(request: NextRequest) {
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
  }

  const { success, resetAt } = rateLimit(`env-download:${user.id}`, 5);
  if (!success) {
    return NextResponse.json(
      { error: '요청이 너무 많습니다. 잠시 후 다시 시도해주세요.' },
      { status: 429, headers: { 'Retry-After': String(Math.max(1, Math.ceil((resetAt - Date.now()) / 1000))) } }
    );
  }

  const { searchParams } = new URL(request.url);
  const projectId = searchParams.get('project_id');
  const environment = searchParams.get('environment') || 'development';

  if (!projectId) {
    return NextResponse.json({ error: 'Missing project_id' }, { status: 400 });
  }

  // Verify project ownership
  const { data: project } = await supabase
    .from('projects')
    .select('id, name')
    .eq('id', projectId)
    .eq('user_id', user.id)
    .single();

  if (!project) {
    return NextResponse.json({ error: 'Project not found' }, { status: 404 });
  }

  const { data: envVars } = await supabase
    .from('environment_variables')
    .select('*')
    .eq('project_id', projectId)
    .eq('environment', environment)
    .order('key_name');

  if (!envVars || envVars.length === 0) {
    return new NextResponse('# No environment variables found\n', {
      status: 200,
      headers: {
        'Content-Type': 'text/plain',
        'Content-Disposition': `attachment; filename=".env.${environment === 'development' ? 'local' : environment}"`,
      },
    });
  }

  const lines: string[] = [
    `# ${project.name} - ${environment} environment`,
    `# Generated by Linkmap on ${new Date().toISOString()}`,
    '',
  ];

  for (const envVar of envVars) {
    if (envVar.description) {
      lines.push(`# ${envVar.description}`);
    }
    try {
      const value = decrypt(envVar.encrypted_value);
      lines.push(`${envVar.key_name}=${value}`);
    } catch {
      lines.push(`# ERROR: Could not decrypt ${envVar.key_name}`);
      lines.push(`${envVar.key_name}=`);
    }
    lines.push('');
  }

  await logAudit(user.id, {
    action: 'env_var.bulk_decrypt',
    resourceType: 'environment_variable',
    resourceId: projectId,
    details: { environment, count: envVars.length },
  });

  const content = lines.join('\n');
  const filename = environment === 'development' ? '.env.local' : `.env.${environment}`;

  return new NextResponse(content, {
    status: 200,
    headers: {
      'Content-Type': 'text/plain',
      'Content-Disposition': `attachment; filename="${filename}"`,
    },
  });
}
