import { NextRequest, NextResponse } from 'next/server';
import { createClient } from '@/lib/supabase/server';
import { decrypt } from '@/lib/crypto';
import { requireMfa } from '@/lib/api/mfa-guard';
import { unauthorizedError, apiError, notFoundError } from '@/lib/api/errors';
import { logAudit } from '@/lib/audit';

export async function GET(request: NextRequest) {
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) return unauthorizedError();

  const mfaResponse = await requireMfa(supabase);
  if (mfaResponse) return mfaResponse;

  const { searchParams } = new URL(request.url);
  const projectId = searchParams.get('project_id');
  const environment = searchParams.get('environment') || 'development';

  if (!projectId) return apiError('project_id가 필요합니다', 400);

  // Verify project ownership
  const { data: project } = await supabase
    .from('projects')
    .select('id, name')
    .eq('id', projectId)
    .eq('user_id', user.id)
    .single();

  if (!project) return notFoundError('프로젝트');

  const { data: envVars } = await supabase
    .from('environment_variables')
    .select('*')
    .eq('project_id', projectId)
    .eq('environment', environment)
    .order('key_name');

  if (!envVars || envVars.length === 0) {
    return new NextResponse('# No environment variables found\n', {
      status: 200,
      headers: {
        'Content-Type': 'text/plain',
        'Content-Disposition': `attachment; filename=".env.${environment === 'development' ? 'local' : environment}"`,
      },
    });
  }

  const lines: string[] = [
    `# ${project.name} - ${environment} environment`,
    `# Generated by Linkmap on ${new Date().toISOString()}`,
    '',
  ];

  const BATCH_SIZE = 50;
  for (let i = 0; i < envVars.length; i += BATCH_SIZE) {
    const batch = envVars.slice(i, i + BATCH_SIZE);
    for (const envVar of batch) {
      if (envVar.description) {
        lines.push(`# ${envVar.description}`);
      }
      try {
        const value = decrypt(envVar.encrypted_value);
        lines.push(`${envVar.key_name}=${value}`);
      } catch {
        lines.push(`# ERROR: Could not decrypt ${envVar.key_name}`);
        lines.push(`${envVar.key_name}=`);
      }
      lines.push('');
    }
    // Workers CPU 시간 제한 완화를 위한 이벤트루프 양보
    if (i + BATCH_SIZE < envVars.length) {
      await new Promise((resolve) => setTimeout(resolve, 0));
    }
  }

  await logAudit(user.id, {
    action: 'env_var.bulk_decrypt',
    resourceType: 'environment_variable',
    resourceId: projectId,
    details: { environment, count: envVars.length },
  });

  const content = lines.join('\n');
  const filename = environment === 'development' ? '.env.local' : `.env.${environment}`;

  return new NextResponse(content, {
    status: 200,
    headers: {
      'Content-Type': 'text/plain',
      'Content-Disposition': `attachment; filename="${filename}"`,
    },
  });
}
