-- ============================================================
-- 046: 도메인 등록 서비스 6개 DB 반영
-- (국내: Gabia, HostingKR, DotName / 해외: Namecheap, Cloudflare Registrar, GoDaddy)
-- Seed API(개발전용)를 대신해 프로덕션 DB에 직접 upsert
-- ============================================================

-- 1. service_subcategories: domain_registrar 확보
INSERT INTO public.service_subcategories (id, category, name, name_ko, description, description_ko)
VALUES (
  'domain_registrar',
  'domain',
  'Domain Registrar',
  '도메인 등록',
  'Domain registration and DNS management',
  '도메인 등록 및 DNS 관리'
)
ON CONFLICT (id) DO UPDATE SET
  category       = EXCLUDED.category,
  name           = EXCLUDED.name,
  name_ko        = EXCLUDED.name_ko,
  description    = EXCLUDED.description,
  description_ko = EXCLUDED.description_ko;

-- 2. services: 6개 도메인 등록 서비스 upsert (slug 기준 conflict)

-- 2-1. Namecheap
INSERT INTO public.services (
  id, name, slug, category, description, description_ko,
  icon_url, website_url, docs_url, pricing_info, required_env_vars,
  domain, subcategory, popularity_score, difficulty_level, tags,
  alternatives, compatibility, official_sdks,
  free_tier_quality, vendor_lock_in_risk, setup_time_minutes,
  monthly_cost_estimate, dx_score
) VALUES (
  '10000000-0000-4000-a000-000000000051',
  'Namecheap',
  'namecheap',
  'domain',
  '저가 도메인 등록 및 DNS 관리 서비스로, 무료 WHOIS 프라이버시 보호·도메인 이전·DNS 관리 기능을 제공합니다.',
  '저가 도메인 등록 및 DNS 관리 서비스로, 무료 WHOIS 프라이버시 보호·도메인 이전·DNS 관리 기능을 제공합니다.',
  NULL,
  'https://www.namecheap.com',
  'https://www.namecheap.com/support/knowledgebase',
  '{"free_tier":false,"free_tier_details":"무료 등급 없음 (기본 도메인 가격: .com $6.49/첫해, $14.98/연장)","plans":[{"name":"Domain Registration","price":".com $6.49~$14.98/년"},{"name":"Domain Hosting Bundle","price":"$1.98~$4.98/월"},{"name":"Premium DNS","price":"무료"},{"name":"SSL Certificate","price":"$8.88/년~"}]}',
  '[{"name":"NAMECHEAP_API_KEY","public":false,"description":"Namecheap API 키","description_ko":"Namecheap API 키"},{"name":"NAMECHEAP_USERNAME","public":false,"description":"Namecheap 계정 사용자명","description_ko":"Namecheap 계정 사용자명"}]',
  'infrastructure',
  'domain_registrar',
  82,
  'beginner',
  ARRAY['domain','registrar','dns','whois','cheap','transfer','privacy','bulk-registration'],
  ARRAY['godaddy','cloudflare-registrar','gabia'],
  '{"framework":["next","express","django","rails"],"language":["javascript","typescript","python","ruby","php"]}',
  '{"javascript":"https://github.com/Namecheap/namecheap-api-sdk-js","php":"https://github.com/Namecheap/namecheap-api"}',
  'none',
  'low',
  5,
  '{"starter":"$0.54/월 (.com)","growth":"$1.25~$4.98/월","enterprise":"문의"}',
  8.0
)
ON CONFLICT (slug) DO UPDATE SET
  id                    = EXCLUDED.id,
  name                  = EXCLUDED.name,
  category              = EXCLUDED.category,
  description           = EXCLUDED.description,
  description_ko        = EXCLUDED.description_ko,
  website_url           = EXCLUDED.website_url,
  docs_url              = EXCLUDED.docs_url,
  pricing_info          = EXCLUDED.pricing_info,
  required_env_vars     = EXCLUDED.required_env_vars,
  domain                = EXCLUDED.domain,
  subcategory           = EXCLUDED.subcategory,
  popularity_score      = EXCLUDED.popularity_score,
  difficulty_level      = EXCLUDED.difficulty_level,
  tags                  = EXCLUDED.tags,
  alternatives          = EXCLUDED.alternatives,
  compatibility         = EXCLUDED.compatibility,
  official_sdks         = EXCLUDED.official_sdks,
  free_tier_quality     = EXCLUDED.free_tier_quality,
  vendor_lock_in_risk   = EXCLUDED.vendor_lock_in_risk,
  setup_time_minutes    = EXCLUDED.setup_time_minutes,
  monthly_cost_estimate = EXCLUDED.monthly_cost_estimate,
  dx_score              = EXCLUDED.dx_score;

-- 2-2. Cloudflare Registrar
INSERT INTO public.services (
  id, name, slug, category, description, description_ko,
  icon_url, website_url, docs_url, pricing_info, required_env_vars,
  domain, subcategory, popularity_score, difficulty_level, tags,
  alternatives, compatibility, official_sdks,
  free_tier_quality, vendor_lock_in_risk, setup_time_minutes,
  monthly_cost_estimate, dx_score
) VALUES (
  '10000000-0000-4000-a000-000000000052',
  'Cloudflare Registrar',
  'cloudflare-registrar',
  'domain',
  'Cloudflare의 도메인 등록 서비스로, 마크업 없는 투명한 가격·DNS 통합·DNSSEC 자동화를 제공합니다.',
  'Cloudflare의 도메인 등록 서비스로, 마크업 없는 투명한 가격·DNS 통합·DNSSEC 자동화를 제공합니다.',
  NULL,
  'https://www.cloudflare.com/products/registrar/',
  'https://developers.cloudflare.com/registrar/',
  '{"free_tier":false,"free_tier_details":"무료 등급 없음 (마크업 없는 레지스트리 가격 청구)","plans":[{"name":"Domain Registration","price":".com $10.46/년 (마크업 없음)"},{"name":"Enterprise Transfer","price":"무료 이전"},{"name":"DNS Management","price":"포함 (무료)"},{"name":"DNSSEC","price":"자동 활성화 (무료)"}]}',
  '[{"name":"CLOUDFLARE_API_TOKEN","public":false,"description":"Cloudflare API 토큰 (도메인 관리 권한)","description_ko":"Cloudflare API 토큰 (도메인 관리 권한)"},{"name":"CLOUDFLARE_ZONE_ID","public":false,"description":"Cloudflare Zone ID","description_ko":"Cloudflare Zone ID"}]',
  'infrastructure',
  'domain_registrar',
  75,
  'intermediate',
  ARRAY['domain','registrar','dns','dnssec','cloudflare','transparent-pricing','api','cdn-integration'],
  ARRAY['namecheap','godaddy'],
  '{"framework":["next","express","django","rails","remix"],"language":["javascript","typescript","python","ruby","go"]}',
  '{"javascript":"https://github.com/cloudflare/cloudflare-typescript","python":"https://github.com/cloudflare/python-cloudflare","go":"https://github.com/cloudflare/cloudflare-go"}',
  'none',
  'low',
  10,
  '{"starter":"$0.87/월 (.com)","growth":"$5~$20/월 (멀티 도메인)","enterprise":"문의"}',
  8.5
)
ON CONFLICT (slug) DO UPDATE SET
  id                    = EXCLUDED.id,
  name                  = EXCLUDED.name,
  category              = EXCLUDED.category,
  description           = EXCLUDED.description,
  description_ko        = EXCLUDED.description_ko,
  website_url           = EXCLUDED.website_url,
  docs_url              = EXCLUDED.docs_url,
  pricing_info          = EXCLUDED.pricing_info,
  required_env_vars     = EXCLUDED.required_env_vars,
  domain                = EXCLUDED.domain,
  subcategory           = EXCLUDED.subcategory,
  popularity_score      = EXCLUDED.popularity_score,
  difficulty_level      = EXCLUDED.difficulty_level,
  tags                  = EXCLUDED.tags,
  alternatives          = EXCLUDED.alternatives,
  compatibility         = EXCLUDED.compatibility,
  official_sdks         = EXCLUDED.official_sdks,
  free_tier_quality     = EXCLUDED.free_tier_quality,
  vendor_lock_in_risk   = EXCLUDED.vendor_lock_in_risk,
  setup_time_minutes    = EXCLUDED.setup_time_minutes,
  monthly_cost_estimate = EXCLUDED.monthly_cost_estimate,
  dx_score              = EXCLUDED.dx_score;

-- 2-3. GoDaddy
INSERT INTO public.services (
  id, name, slug, category, description, description_ko,
  icon_url, website_url, docs_url, pricing_info, required_env_vars,
  domain, subcategory, popularity_score, difficulty_level, tags,
  alternatives, compatibility, official_sdks,
  free_tier_quality, vendor_lock_in_risk, setup_time_minutes,
  monthly_cost_estimate, dx_score
) VALUES (
  '10000000-0000-4000-a000-000000000053',
  'GoDaddy',
  'godaddy',
  'domain',
  '세계 최대 도메인 등록업체로, 도메인 등록·호스팅·이메일·웹사이트 빌더·SSL 인증서를 통합 제공합니다.',
  '세계 최대 도메인 등록업체로, 도메인 등록·호스팅·이메일·웹사이트 빌더·SSL 인증서를 통합 제공합니다.',
  NULL,
  'https://www.godaddy.com',
  'https://developer.godaddy.com',
  '{"free_tier":true,"free_tier_details":"프로모션: .com 첫해 $0.01 (연장 시 $18.99)","plans":[{"name":"Domain Only","price":".com $0.01~$18.99/년 (프로모션)"},{"name":"Starter Hosting","price":"$2.99~$5.99/월"},{"name":"Business Hosting","price":"$5.99~$9.99/월"},{"name":"Enterprise","price":"문의"}]}',
  '[{"name":"GODADDY_API_KEY","public":false,"description":"GoDaddy API 키","description_ko":"GoDaddy API 키"},{"name":"GODADDY_API_SECRET","public":false,"description":"GoDaddy API 시크릿 키","description_ko":"GoDaddy API 시크릿 키"}]',
  'infrastructure',
  'domain_registrar',
  90,
  'beginner',
  ARRAY['domain','registrar','hosting','builder','email','ssl','popular','all-in-one'],
  ARRAY['namecheap','cloudflare-registrar'],
  '{"framework":["next","express","django","rails","wordpress"],"language":["javascript","typescript","python","ruby","php","java"]}',
  '{"php":"https://github.com/godaddy/godaddy-api-php","python":"https://github.com/godaddy/godaddy-python"}',
  'good',
  'medium',
  5,
  '{"starter":"$0.01~$1.58/월 (프로모션)","growth":"$5.99~$9.99/월 (호스팅)","enterprise":"문의"}',
  7.5
)
ON CONFLICT (slug) DO UPDATE SET
  id                    = EXCLUDED.id,
  name                  = EXCLUDED.name,
  category              = EXCLUDED.category,
  description           = EXCLUDED.description,
  description_ko        = EXCLUDED.description_ko,
  website_url           = EXCLUDED.website_url,
  docs_url              = EXCLUDED.docs_url,
  pricing_info          = EXCLUDED.pricing_info,
  required_env_vars     = EXCLUDED.required_env_vars,
  domain                = EXCLUDED.domain,
  subcategory           = EXCLUDED.subcategory,
  popularity_score      = EXCLUDED.popularity_score,
  difficulty_level      = EXCLUDED.difficulty_level,
  tags                  = EXCLUDED.tags,
  alternatives          = EXCLUDED.alternatives,
  compatibility         = EXCLUDED.compatibility,
  official_sdks         = EXCLUDED.official_sdks,
  free_tier_quality     = EXCLUDED.free_tier_quality,
  vendor_lock_in_risk   = EXCLUDED.vendor_lock_in_risk,
  setup_time_minutes    = EXCLUDED.setup_time_minutes,
  monthly_cost_estimate = EXCLUDED.monthly_cost_estimate,
  dx_score              = EXCLUDED.dx_score;

-- 2-4. Gabia (가비아)
INSERT INTO public.services (
  id, name, slug, category, description, description_ko,
  icon_url, website_url, docs_url, pricing_info, required_env_vars,
  domain, subcategory, popularity_score, difficulty_level, tags,
  alternatives, compatibility, official_sdks,
  free_tier_quality, vendor_lock_in_risk, setup_time_minutes,
  monthly_cost_estimate, dx_score
) VALUES (
  '10000000-0000-4000-a000-000000000054',
  'Gabia',
  'gabia',
  'domain',
  '한국 도메인 등록 1위 업체로, 한국 도메인(.kr)·국제 도메인(.com 등)을 제공하며 AI 도메인 추천·웹호스팅·SSL을 지원합니다.',
  '한국 도메인 등록 1위 업체로, 한국 도메인(.kr)·국제 도메인(.com 등)을 제공하며 AI 도메인 추천·웹호스팅·SSL을 지원합니다.',
  NULL,
  'https://domain.gabia.com',
  'https://www.gabia.com/support/documentation',
  '{"free_tier":false,"free_tier_details":"무료 등급 없음 (.kr 기본: $12/년, .com 기본: $8.5/년)","plans":[{"name":".KR Domain","price":"$12/년"},{"name":".COM Domain","price":"$8.5/년"},{"name":"Web Hosting","price":"$2.5~$5/월"},{"name":"SSL Certificate","price":"$40~$200/년"}]}',
  '[{"name":"GABIA_API_KEY","public":false,"description":"가비아 API 키","description_ko":"가비아 API 키"},{"name":"GABIA_ACCOUNT_ID","public":false,"description":"가비아 계정 ID","description_ko":"가비아 계정 ID"}]',
  'infrastructure',
  'domain_registrar',
  88,
  'beginner',
  ARRAY['domain','registrar','.kr','korea','local','ai-recommendation','hosting','ssl'],
  ARRAY['hosting-kr','dotname'],
  '{"framework":["next","express","django","rails"],"language":["javascript","typescript","python","ruby","php"]}',
  '{"javascript":"https://github.com/gabia/gabia-api-sdk","python":"https://github.com/gabia/gabia-python-sdk"}',
  'none',
  'low',
  5,
  '{"starter":"$1/월 (.kr)","growth":"$2.5~$5/월 (호스팅)","enterprise":"문의"}',
  7.5
)
ON CONFLICT (slug) DO UPDATE SET
  id                    = EXCLUDED.id,
  name                  = EXCLUDED.name,
  category              = EXCLUDED.category,
  description           = EXCLUDED.description,
  description_ko        = EXCLUDED.description_ko,
  website_url           = EXCLUDED.website_url,
  docs_url              = EXCLUDED.docs_url,
  pricing_info          = EXCLUDED.pricing_info,
  required_env_vars     = EXCLUDED.required_env_vars,
  domain                = EXCLUDED.domain,
  subcategory           = EXCLUDED.subcategory,
  popularity_score      = EXCLUDED.popularity_score,
  difficulty_level      = EXCLUDED.difficulty_level,
  tags                  = EXCLUDED.tags,
  alternatives          = EXCLUDED.alternatives,
  compatibility         = EXCLUDED.compatibility,
  official_sdks         = EXCLUDED.official_sdks,
  free_tier_quality     = EXCLUDED.free_tier_quality,
  vendor_lock_in_risk   = EXCLUDED.vendor_lock_in_risk,
  setup_time_minutes    = EXCLUDED.setup_time_minutes,
  monthly_cost_estimate = EXCLUDED.monthly_cost_estimate,
  dx_score              = EXCLUDED.dx_score;

-- 2-5. HostingKR (호스팅케이알)
INSERT INTO public.services (
  id, name, slug, category, description, description_ko,
  icon_url, website_url, docs_url, pricing_info, required_env_vars,
  domain, subcategory, popularity_score, difficulty_level, tags,
  alternatives, compatibility, official_sdks,
  free_tier_quality, vendor_lock_in_risk, setup_time_minutes,
  monthly_cost_estimate, dx_score
) VALUES (
  '10000000-0000-4000-a000-000000000055',
  'HostingKR',
  'hosting-kr',
  'domain',
  '한국의 신뢰할 수 있는 도메인 등록·호스팅 서비스로, 500개 이상의 도메인 확장자·DNS 관리·웹호스팅·이메일 서비스를 제공합니다.',
  '한국의 신뢰할 수 있는 도메인 등록·호스팅 서비스로, 500개 이상의 도메인 확장자·DNS 관리·웹호스팅·이메일 서비스를 제공합니다.',
  NULL,
  'https://www.hosting.kr',
  'https://www.hosting.kr/support',
  '{"free_tier":false,"free_tier_details":"무료 등급 없음 (.kr 기본: $10~$12/년, .com 기본: $8/년)","plans":[{"name":".KR Domain","price":"$10~$12/년"},{"name":".COM Domain","price":"$8/년"},{"name":"Basic Hosting","price":"$2.5/월"},{"name":"Premium Hosting","price":"$5~$10/월"}]}',
  '[{"name":"HOSTING_KR_API_KEY","public":false,"description":"호스팅케이알 API 키","description_ko":"호스팅케이알 API 키"},{"name":"HOSTING_KR_ACCOUNT_ID","public":false,"description":"호스팅케이알 계정 ID","description_ko":"호스팅케이알 계정 ID"}]',
  'infrastructure',
  'domain_registrar',
  78,
  'beginner',
  ARRAY['domain','registrar','.kr','korea','hosting','email','dns','local'],
  ARRAY['gabia','dotname'],
  '{"framework":["next","express","django","rails"],"language":["javascript","typescript","python","ruby","php"]}',
  '{"javascript":"https://github.com/hosting-kr/hosting-kr-api"}',
  'none',
  'low',
  5,
  '{"starter":"$0.8~$1/월 (.kr)","growth":"$2.5~$5/월 (호스팅)","enterprise":"문의"}',
  7.0
)
ON CONFLICT (slug) DO UPDATE SET
  id                    = EXCLUDED.id,
  name                  = EXCLUDED.name,
  category              = EXCLUDED.category,
  description           = EXCLUDED.description,
  description_ko        = EXCLUDED.description_ko,
  website_url           = EXCLUDED.website_url,
  docs_url              = EXCLUDED.docs_url,
  pricing_info          = EXCLUDED.pricing_info,
  required_env_vars     = EXCLUDED.required_env_vars,
  domain                = EXCLUDED.domain,
  subcategory           = EXCLUDED.subcategory,
  popularity_score      = EXCLUDED.popularity_score,
  difficulty_level      = EXCLUDED.difficulty_level,
  tags                  = EXCLUDED.tags,
  alternatives          = EXCLUDED.alternatives,
  compatibility         = EXCLUDED.compatibility,
  official_sdks         = EXCLUDED.official_sdks,
  free_tier_quality     = EXCLUDED.free_tier_quality,
  vendor_lock_in_risk   = EXCLUDED.vendor_lock_in_risk,
  setup_time_minutes    = EXCLUDED.setup_time_minutes,
  monthly_cost_estimate = EXCLUDED.monthly_cost_estimate,
  dx_score              = EXCLUDED.dx_score;

-- 2-6. DotName (닷네임)
INSERT INTO public.services (
  id, name, slug, category, description, description_ko,
  icon_url, website_url, docs_url, pricing_info, required_env_vars,
  domain, subcategory, popularity_score, difficulty_level, tags,
  alternatives, compatibility, official_sdks,
  free_tier_quality, vendor_lock_in_risk, setup_time_minutes,
  monthly_cost_estimate, dx_score
) VALUES (
  '10000000-0000-4000-a000-000000000056',
  'DotName',
  'dotname',
  'domain',
  '국내 도메인 등록 전문 기업으로, 한국 도메인(.kr)·국제 도메인 등록·DNS 관리·무료 웹호스팅을 제공합니다.',
  '국내 도메인 등록 전문 기업으로, 한국 도메인(.kr)·국제 도메인 등록·DNS 관리·무료 웹호스팅을 제공합니다.',
  NULL,
  'https://www.dotname.co.kr',
  'https://www.dotname.co.kr/support',
  '{"free_tier":true,"free_tier_details":"도메인 등록 시 무료 웹호스팅 제공","plans":[{"name":".KR Domain","price":"$10~$12/년 + 무료 호스팅"},{"name":".COM Domain","price":"$8~$9/년 + 무료 호스팅"},{"name":"Free Hosting","price":"$0/월 (도메인 등록 포함)"},{"name":"Premium Add-ons","price":"$2~$10/월"}]}',
  '[{"name":"DOTNAME_API_KEY","public":false,"description":"닷네임 API 키","description_ko":"닷네임 API 키"},{"name":"DOTNAME_ACCOUNT_ID","public":false,"description":"닷네임 계정 ID","description_ko":"닷네임 계정 ID"}]',
  'infrastructure',
  'domain_registrar',
  72,
  'beginner',
  ARRAY['domain','registrar','.kr','korea','free-hosting','dns','local','affordable'],
  ARRAY['gabia','hosting-kr'],
  '{"framework":["next","express","django","rails"],"language":["javascript","typescript","python","ruby","php"]}',
  '{"javascript":"https://github.com/dotname/dotname-api-js"}',
  'excellent',
  'low',
  5,
  '{"starter":"$0/월 (무료 호스팅 포함)","growth":"$0.8~$1/월 (.kr 도메인)","enterprise":"문의"}',
  7.5
)
ON CONFLICT (slug) DO UPDATE SET
  id                    = EXCLUDED.id,
  name                  = EXCLUDED.name,
  category              = EXCLUDED.category,
  description           = EXCLUDED.description,
  description_ko        = EXCLUDED.description_ko,
  website_url           = EXCLUDED.website_url,
  docs_url              = EXCLUDED.docs_url,
  pricing_info          = EXCLUDED.pricing_info,
  required_env_vars     = EXCLUDED.required_env_vars,
  domain                = EXCLUDED.domain,
  subcategory           = EXCLUDED.subcategory,
  popularity_score      = EXCLUDED.popularity_score,
  difficulty_level      = EXCLUDED.difficulty_level,
  tags                  = EXCLUDED.tags,
  alternatives          = EXCLUDED.alternatives,
  compatibility         = EXCLUDED.compatibility,
  official_sdks         = EXCLUDED.official_sdks,
  free_tier_quality     = EXCLUDED.free_tier_quality,
  vendor_lock_in_risk   = EXCLUDED.vendor_lock_in_risk,
  setup_time_minutes    = EXCLUDED.setup_time_minutes,
  monthly_cost_estimate = EXCLUDED.monthly_cost_estimate,
  dx_score              = EXCLUDED.dx_score;
